---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: output
  params:
    - name: repo-url
      type: string
    - name: branch
      type: string
      default: main
    - name: app-name
      type: string
    - name: build-image
      type: string
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output

    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: output
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
      runAfter:
        - cleanup

    - name: lint
      taskRef:
        name: flake8
        kind: ClusterTask
      workspaces:
        - name: source
          workspace: output
      params:
        - name: args
          value: ["--count", "--max-complexity=10", "--max-line-length=127", "--statistics"]
      runAfter:
        - clone

    - name: tests
      taskRef:
        name: nose
      workspaces:
        - name: source
          workspace: output
      params:
        - name: args
          value: "-v --with-spec --spec-color"
      runAfter:
        - lint

    - name: build
      taskRef:
        name: buildah
        kind: ClusterTask
      workspaces:
        - name: source
          workspace: output
      params:
        - name: IMAGE
          value: $(params.build-image)
      runAfter:
        - tests

    - name: deploy
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
